##########################################
# Function to analyze the data generated by dat.gen() function found in the p4_1_data_generation.R program file,
#   data analysis involves performing variable selection in linear regression using the 5+2 different methods specified
##########################################

library(olsrr)
library(glmnet)
library(stats)

analyze.data <- function(n, rho, seed){
  
  #Generate data
  set.seed(seed)
  test <- dat.gen(n, rho)

  #Fit full model
  fullmodel <- lm(y ~ . , data=test)
  
  #Method 1: backwards using p-value
  back.sel.p <- olsrr::ols_step_backward_p(fullmodel, p_val=0.05)#, progress = TRUE, details = TRUE)
  #The line below returns a matrix with 4 columns that is fed into compute.metrics() function
  bp <- cbind(summary(back.sel.p$model)$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(back.sel.p$model, level = 0.95)[-1,])#remove the intercept term
  
  #Method 2: backwards using AIC
  back.sel.aic <- stats::step(object = fullmodel, direction = 'backward', trace = 0, k = 2)
  ba <- cbind(summary(back.sel.aic)$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(back.sel.aic, level = 0.95)[-1,])
  
  #Method 3: backwards using BIC
  back.sel.bic <- stats::step(object = fullmodel, direction = 'backward', trace = 0, k = log(nrow(test)))
  bb <- cbind(summary(back.sel.bic)$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(back.sel.bic, level = 0.95)[-1,])
  
  set.seed(seed) #Repeatedly calling set.seed out of habit and just to be sure
  # Performing variable selection using LASSO 
  lasso_mod <- glmnet::cv.glmnet(x = as.matrix(test[,-1]), y = test[,1], family = "gaussian", alpha = 1,   standardize = TRUE, type.measure = "mse", nfolds = 5)
  lam <- cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(lasso_mod, s = 'lambda.min'))[coef(lasso_mod, s = 'lambda.min')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,]) #LASSO with min lambda
  la1 <- cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(lasso_mod, s = 'lambda.1se'))[coef(lasso_mod, s = 'lambda.1se')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,]) #LASSO with 1se lambda
  
  set.seed(seed)
  # Performing variable selection using Elastic Net with alpha = 0.5
  elnet_mod1 <- glmnet::cv.glmnet(x = as.matrix(test[,-1]), y = test[,1], family = "gaussian", alpha = 0.5, standardize = TRUE, type.measure = "mse", nfolds = 5)
  em <- cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(elnet_mod1, s = 'lambda.min'))[coef(elnet_mod1, s = 'lambda.min')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])
  e1 <- cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(elnet_mod1, s = 'lambda.1se'))[coef(elnet_mod1, s = 'lambda.1se')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])

  set.seed(seed)
  # Performing variable selection using Elastic Net with alpha = 0.95 (to see if this handles instances where there is higher multicollinearity)
  elnet_mod2 <- glmnet::cv.glmnet(x = as.matrix(test[,-1]), y = test[,1], family = "gaussian", alpha = 0.95, standardize = TRUE, type.measure = "mse", nfolds = 5)
  em2 <- cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(elnet_mod2, s = 'lambda.min'))[coef(elnet_mod2, s = 'lambda.min')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])
  e12 <- cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(elnet_mod2, s = 'lambda.1se'))[coef(elnet_mod2, s = 'lambda.1se')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])
  
  ## Oracle benchmark 
  #Suggested by Copilot for troubleshooting and comparing each variable selection method to the truth (the Oracle)
  oracle_mod <- lm(y ~ v1 + v2 + v3 + v4 + v5, data = test)
  om <- cbind(summary(oracle_mod)$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(oracle_mod, level = 0.95)[-1, ])
  
  res_all <- data.frame() #Initiate dataframe to store all matrices
  
  #Makes a call to compute.metrics() to estimate the performance metrics and rowbinds all the metrics for each model
  res_all <- rbind(res_all, cbind(compute.metrics(bp), method = "2_Backwards p-value"))
  res_all <- rbind(res_all, cbind(compute.metrics(ba), method = "3_Backwards AIC"))
  res_all <- rbind(res_all, cbind(compute.metrics(bb), method = "4_Backwards BIC"))
  res_all <- rbind(res_all, cbind(compute.metrics(lam), method = "5_LASSO Lambda-min"))
  res_all <- rbind(res_all, cbind(compute.metrics(la1), method = "6_LASSO Lambda-1se"))
  res_all <- rbind(res_all, cbind(compute.metrics(em), method = "7_ElasticNet Lambda-min"))
  res_all <- rbind(res_all, cbind(compute.metrics(e1), method = "8_ElasticNet Lambda-1se"))
  res_all <- rbind(res_all, cbind(compute.metrics(em2), method = "9_ElasticNet (a.95) Lambda-min"))
  res_all <- rbind(res_all, cbind(compute.metrics(e12), method = "91_ElasticNet (a.95) Lambda-1se"))
  res_all <- rbind(res_all, cbind(compute.metrics(om), method = "1_Oracle (The Truth)"))
  
  #Add n, rho, and seed to differentiate analysis scenarios
  res_all$n   <- n
  res_all$rho <- rho
  res_all$seed <- seed
  
  #rownames(res_all) <- res_all$method
  rownames(res_all) <- 1:nrow(res_all)
  
  return(res_all) #Return performance metrics for each variable selection method
}
