##########################################
# Function to analyze the data generated by dat.gen() function found in the p4_data_generation.R program file,
#   data analysis involves performing variable selection in liinear regression using the 5+2 different methods specified
##########################################

library(olsrr)
library(glmnet)



set.seed(1)
test <- dat.gen(250,0.7)



analyze.data <- function(n, rho){
  
  #Generate data
  set.seed(1)
  test <- dat.gen(n, rho)

  #Fit full model
  fullmodel <- lm(y ~ . , data=test)
  
  #Method 1: backwards using p-value
  back.sel.p <- olsrr::ols_step_backward_p(fullmodel, p_val=0.05)#, progress = TRUE, details = TRUE)
  bp <- cbind(summary(back.sel.p$model)$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(back.sel.p$model, level = 0.95)[-1,])
  
  #Method 2: backwards using AIC
  back.sel.aic <- stats::step(object = fullmodel, direction = 'backward', trace = 0, k = 2)
  ba <- cbind(summary(back.sel.aic)$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(back.sel.aic, level = 0.95)[-1,])
  
  #Method 3: backwards using BIC
  back.sel.bic <- stats::step(object = fullmodel, direction = 'backward', trace = 0, k = log(nrow(test)))
  bb <- cbind(summary(back.sel.bic)$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(back.sel.bic, level = 0.95)[-1,])
  
  set.seed(463784)
  # basic call to glmnet-uses a range of lambda values:
  lasso_mod <- glmnet::cv.glmnet(x = as.matrix(test[,-1]), y = test[,1], family = "gaussian", alpha = 1,   standardize = TRUE, type.measure = "mse", nfolds = 5)
  lm <- cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(lasso_mod, s = 'lambda.min'))[coef(lasso_mod, s = 'lambda.min')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])
  l1 <- cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(lasso_mod, s = 'lambda.1se'))[coef(lasso_mod, s = 'lambda.1se')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])
  
  set.seed(463784)
  elnet_mod1 <- glmnet::cv.glmnet(x = as.matrix(test[,-1]), y = test[,1], family = "gaussian", alpha = 0.5, standardize = TRUE, type.measure = "mse", nfolds = 5)
  em <- cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(elnet_mod1, s = 'lambda.min'))[coef(elnet_mod1, s = 'lambda.min')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])
  e1 <- cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(elnet_mod1, s = 'lambda.1se'))[coef(elnet_mod1, s = 'lambda.1se')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])

  
  res_all <- data.frame()
  
  res_all <- rbind(res_all, cbind(compute_metrics(bp), method = "Backwards p-value"))
  res_all <- rbind(res_all, cbind(compute_metrics(ba), method = "Backwards AIC"))
  res_all <- rbind(res_all, cbind(compute_metrics(bb), method = "Backwards BIC"))
  res_all <- rbind(res_all, cbind(compute_metrics(lm), method = "LASSO Lambda-min"))
  res_all <- rbind(res_all, cbind(compute_metrics(l1), method = "LASSO Lambda-1se"))
  res_all <- rbind(res_all, cbind(compute_metrics(em), method = "ElasticNet Lambda-min"))
  res_all <- rbind(res_all, cbind(compute_metrics(e1), method = "ElasticNet Lambda-1se"))
  
  ## ---- add n and rho (same for all rows) ----
  res_all$n   <- n
  res_all$rho <- rho

  return(res_all)

}





analyze.data(n=500, rho=0.7)




#determine bias and co
compute_metrics <- function(mat) {
  
  ## ---- true beta ----
  true_beta <- c(0.5/3, 1/3, 1.5/3, 2.0/3, 2.5/3, rep(0, 15))
  names(true_beta) <- paste0("v", 1:20)
  
  ## ---- initialize result data frame (one row) ----
  res <- data.frame(matrix(ncol = 60, nrow = 0))
  names(res) <- c(
    paste0("bias", 1:20),   # bias
    paste0("p.sig", 1:20),  # significance indicator
    paste0("cov", 1:20)     # coverage indicator
  )
  
  new_row <- res[0, ][1, ]
  
  ## ---- loop over all 20 possible variables ----
  for (j in 1:20) {
    
    vname <- paste0("v", j)
    bname <- paste0("bias", j)
    pname <- paste0("p.sig", j)
    cname <- paste0("cov", j)
    
    if (vname %in% rownames(mat)) {
      
      ## Bias
      new_row[[bname]] <- mat[vname, "Estimate"] - true_beta[vname]
      
      ## Significance indicator
      new_row[[pname]] <- as.integer(
        mat[vname, "Pr(>|t|)"] <= 0.05
      )
      
      ## Coverage indicator
      new_row[[cname]] <- as.integer(
        mat[vname, "2.5 %"] <= true_beta[vname] &&
          true_beta[vname] <= mat[vname, "97.5 %"]
      )
      
    } else {
      
      ## Variable not selected
      new_row[[bname]] <- NA_real_
      new_row[[pname]] <- 0
      new_row[[cname]] <- 0
    }
  }
  
  ## ---- append and return ----
  res <- rbind(res, new_row)
  return(res)
}







#Generate data
set.seed(1)
test <- dat.gen(250,0)

#Fit full model
fullmodel <- lm(y ~ . , data=test)

#Method 1: backwards using p-value
back.sel.p <- olsrr::ols_step_backward_p(fullmodel, p_val=0.05)#, progress = TRUE, details = TRUE)
cbind(summary(back.sel.p$model)$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(back.sel.p$model, level = 0.95)[-1,])

#Method 2: backwards using AIC
back.sel.aic <- stats::step(object = fullmodel, direction = 'backward', trace = 0, k = 2)
cbind(summary(back.sel.aic)$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(back.sel.aic, level = 0.95)[-1,])

#Method 3: backwards using BIC
back.sel.bic <- stats::step(object = fullmodel, direction = 'backward', trace = 0, k = log(nrow(test)))
cbind(summary(back.sel.bic)$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(back.sel.bic, level = 0.95)[-1,])

set.seed(463784)
# basic call to glmnet-uses a range of lambda values:
lasso_mod <- glmnet::cv.glmnet(x = as.matrix(test[,-1]), y = test[,1], family = "gaussian", alpha = 1,   standardize = TRUE, type.measure = "mse", nfolds = 5)
cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(lasso_mod, s = 'lambda.min'))[coef(lasso_mod, s = 'lambda.min')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])
cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(lasso_mod, s = 'lambda.1se'))[coef(lasso_mod, s = 'lambda.1se')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])

set.seed(463784)
elnet_mod1 <- glmnet::cv.glmnet(x = as.matrix(test[,-1]), y = test[,1], family = "gaussian", alpha = 0.5, standardize = TRUE, type.measure = "mse", nfolds = 5)
cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(elnet_mod1, s = 'lambda.min'))[coef(elnet_mod1, s = 'lambda.min')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])
cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(elnet_mod1, s = 'lambda.1se'))[coef(elnet_mod1, s = 'lambda.1se')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])


#Extra work (may include later)
set.seed(463784)
elnet_mod2 <- glmnet::cv.glmnet(x = as.matrix(test[,-1]), y = test[,1], family = "gaussian", alpha = 0.75, standardize = TRUE, type.measure = "mse", nfolds = 5)
cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(elnet_mod2, s = 'lambda.min'))[coef(elnet_mod2, s = 'lambda.min')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])
cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(elnet_mod2, s = 'lambda.1se'))[coef(elnet_mod2, s = 'lambda.1se')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])

set.seed(463784)
elnet_mod3 <- glmnet::cv.glmnet(x = as.matrix(test[,-1]), y = test[,1], family = "gaussian", alpha = 0.99, standardize = TRUE, type.measure = "mse", nfolds = 5)
cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(elnet_mod3, s = 'lambda.min'))[coef(elnet_mod3, s = 'lambda.min')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])
cbind(summary(a<-lm(y ~ ., data = test[, c("y",rownames(coef(elnet_mod3, s = 'lambda.1se'))[coef(elnet_mod3, s = 'lambda.1se')[,1] != 0][-1])]))$coefficients[-1, c("Estimate", "Pr(>|t|)")], confint(a, level = 0.95)[-1,])















 coef(lasso_mod, s = 'lambda.min')
rownames(coef(lasso_mod, s = 'lambda.min'))






coef(lasso_mod, s = 'lambda.1se')



lasso_mod$lambda.min
lasso_mod_cv$lambda.1se



sol <- coef(lasso_mod_cv, s = 'lambda.1se') 
nsol <- rownames(sol)
nsol <- nsol[sol[,1] != 0]
nsol <- setdiff(nsol, '(Intercept)')

lm_fit <- lm(y ~ . , data = dat2[, nsol])

summary(lm_fit)






plot(lasso_mod)
plot(elnet_mod1)
plot(elnet_mod2)
plot(elnet_mod3)






summary(back.sel.p$model)$coefficients[-1, c("Estimate", "Pr(>|t|)")]








Methods
1) backward selection based on F-test and p-value
2) AIC
3) BIC
4) LASSO, 2 choices of lambda (lambda: min and 1se) ==> lm fit, debiased LASSO, and/or post-selection inference
5) Elastic net, 2 choices of lambda (lambda: min and 1se) ==> lm fit, debiased LASSO, and/or post-selection inference







res <- data.frame(matrix(ncol = 60, nrow = 0))
names(res) <- c(paste0("v", 1:20), paste0("p", 1:20), paste0("c", 1:20))

## ----- True beta values -----
true_beta <- c(0.5/3, 1/3, 1.5/3, 2.0/3, 2.5/3, rep(0, 15))
names(true_beta) <- paste0("v", 1:20)

## ----- Extract estimates and p-values (intercept removed) -----
coef_tab <- data.frame(
  summary(back.sel.p$model)$coefficients[-1, c("Estimate", "Pr(>|t|)")]
)

## ----- Extract 95% confidence intervals -----
ci_tab <- confint(back.sel.p$model, level = 0.95)

## ----- Initialize a new empty row -----
new_row <- res[0, ][1, ]

## ----- Loop over all 20 possible variables -----
for (j in 1:20) {
  
  vname <- paste0("v", j)
  pname <- paste0("p", j)
  cname <- paste0("c", j)
  
  if (vname %in% rownames(coef_tab)) {
    
    ## ----- Bias -----
    new_row[[vname]] <- coef_tab[vname, "Estimate"] - true_beta[vname]
    
    ## ----- Significance indicator -----
    new_row[[pname]] <- as.integer(
      coef_tab[vname, "Pr...t.."] <= 0.05
    )
    
    ## ----- Coverage indicator -----
    new_row[[cname]] <- as.integer(
      ci_tab[vname, 1] <= true_beta[vname] &&
        true_beta[vname] <= ci_tab[vname, 2]
    )
    
  } else {
    
    ## ----- Variable not selected -----
    new_row[[vname]] <- NA_real_  # bias undefined
    new_row[[pname]] <- 0         # not significant
    new_row[[cname]] <- 0         # no coverage
  }
}

## ----- Append to df -----
res <- rbind(res, new_row)

c



#Methods





                   
                   
                   
summary(select_AIC)$coefficients


#MASS
AICbackward<-stepAIC(fullmodel, direction="backward")
summary(AICbackward)$coefficients



library(RcmdrMisc)

fullmodel<-lm(Salary ~ AtBat + Hits + HmRun + Runs + RBI + Walks + Years + CAtBat + CHits + CHmRun + CRuns + CRBI + CWalks + League + Division + PutOuts + Assists + Errors + NewLeague, data=Hitters)

BICbackward<-stepwise(fullmodel, direction="backward",criterion = "BIC")
summary(BICbackward)$coefficients










#end test































true_beta <- c(0.5/3, 1/3, 1.5/3, 2.0/3, 2.5/3, rep(0, 15))
names(true_beta) <- paste0("v", 1:20)

ests <- data.frame(summary(back.sel.p$model)$coefficients[-1, c("Estimate", "Pr(>|t|)")])

ci_tab <- confint(back.sel.p$model, level = 0.95)

# Initialize one empty row (all NA, correct structure)
new_row <- res[0, ][1, ]

# Fill estimates and p-values
for (var in rownames(ests)) {
  v_name <- var
  p_name <- sub("^v", "p", var)
  
  new_row[[v_name]] <- ests[var, "Estimate"]
  new_row[[p_name]] <- ests[var, "Pr...t.."]
}

for (j in 1:20) {
  vname <- paste0("v", j)
  cname <- paste0("c", j)
  
  if (vname %in% rownames(ci_tab)) {
    
    # Confidence interval bounds
    lower <- ci_tab[vname, 1]
    upper <- ci_tab[vname, 2]
    
    # Coverage check
    new_row[[cname]] <- as.integer(
      lower <= true_beta[vname] &&
        true_beta[vname] <= upper
    )
    
  } else {
    
    # Variable not selected → coverage = 0
    new_row[[cname]] <- 0
  }
}


# Append to df
res <- rbind(res, new_row)








Vectorize this for faster Monte Carlo simulations







ests <- data.frame(summary(back.sel.p$model)$coefficients)[-1,]



ests <- summary(back.sel.p$model)$coefficients
ests



g





fullmodel <- lm(y ~ . , data=test)
back.sel.p <- ols_step_backward_p(fullmodel, p_val=0.05)#, progress = TRUE, details = TRUE)
rownames(summary(back.sel.p$model)$coefficients)[-1]



summary(back.sel.p$model)$coefficients




  
  
summary(lm(y~v1+v2+v3+v4+v5,test))




back.lmfit1<-ols_step_backward_p(fullmodel, prem = 0.15)
summary(back.lmfit1$model)
rownames(summary(back.lmfit2$model)$coefficients)[-1]


back.lmfit2<-ols_step_backward_p(fullmodel, p_val=0.05)#, progress = TRUE, details = TRUE)
summary(back.lmfit2$model)






summary(t.fit <- lm(V1 ~ V01+V02+V03+V04+V05+V06+V07+V08+V09+V10+V11+V12+V13+V14+V15+V16+V17+V18+V19+V20, 
                    data=test))

t.sum <- MASS::dropterm(t.fit, test="F")
t.sum <- olsrr::ols_step_backward_p(t.fit, p_va=0.01, hierarchical=TRUE)


## S3 method for class 'lm'
drop1(object, 
      scope, 
      scale = 0, 
      all.cols = TRUE,
      test = "F", 
      k = 2)

lm1 <- lm(Fertility ~ ., data = swiss)
add1(lm1, ~ I(Education^2) + .^2)
drop1(lm1, test = "F")

summary(tst<-step(lm1, direction="backward", k=7))


summary(lm1 <- lm(Fertility ~ ., data = swiss))
slm1 <- step(lm1)
summary(slm1)
slm1$anova


