##########################################
# Function to analyze the data generated by dat.gen() function found in the p4_data_generation.R program file,
#   data analysis involves performing variable selection in liinear regression using the 5+2 different methods specified
##########################################

set.seed(1)
test <- dat.gen(250,0)

analyze.data <- function(){
  
}

summary(t.fit <- lm(V1 ~ V01+V02+V03+V04+V05+V06+V07+V08+V09+V10+V11+V12+V13+V14+V15+V16+V17+V18+V19+V20, 
                    data=test))

t.sum <- MASS::dropterm(t.fit, test="F")
t.sum <- olsrr::ols_step_backward_p(t.fit, p_va=0.01, hierarchical=TRUE)


## S3 method for class 'lm'
drop1(object, 
      scope, 
      scale = 0, 
      all.cols = TRUE,
      test = "F", 
      k = 2)

lm1 <- lm(Fertility ~ ., data = swiss)
add1(lm1, ~ I(Education^2) + .^2)
drop1(lm1, test = "F")

summary(tst<-step(lm1, direction="backward", k=7))


summary(lm1 <- lm(Fertility ~ ., data = swiss))
slm1 <- step(lm1)
summary(slm1)
slm1$anova


